r"""The Cox-Ingersoll-Ross affine term structure, in a numerically stable form.

Under the risk-neutral measure the short rate follows the square-root diffusion
of Cox, Ingersoll and Ross (1985),

.. math::

    dr_t = \kappa (\theta - r_t)\, dt + \sigma \sqrt{r_t}\, dW_t^{\mathbb{Q}},

and the zero-coupon bond price is affine in the state,
:math:`P(0, \tau) = A(\tau) e^{-B(\tau) r_0}`, with :math:`A` and :math:`B` given
in closed form by equation 23 of that paper.

The published form can overflow or lose precision in float64, and the
two obvious repairs each fail somewhere a caller will go.  This module is the
form that does not, so the derivation is recorded rather than left to be
rediscovered.

Writing :math:`\gamma = \sqrt{\kappa^2 + 2\sigma^2}` and :math:`\tau` for the
maturity, equation 23 reads

.. math::

    A(\tau) = \left[
        \frac{2\gamma e^{(\kappa + \gamma)\tau / 2}}
             {(\gamma + \kappa)(e^{\gamma\tau} - 1) + 2\gamma}
    \right]^{2\kappa\theta/\sigma^2},
    \qquad
    B(\tau) = \frac{2(e^{\gamma\tau} - 1)}
                   {(\gamma + \kappa)(e^{\gamma\tau} - 1) + 2\gamma}.

**Failure one: overflow.**  :math:`e^{\gamma\tau}` overflows past
:math:`\gamma\tau \approx 709`, which a thirty-year bond reaches at a
vol-of-rate of roughly 17 or more (depending on mean reversion).  Multiplying numerator and denominator through by
:math:`e^{-\gamma\tau}` and writing :math:`z = e^{-\gamma\tau} \in (0, 1]` fixes
that, and is where most implementations stop.

**Failure two: cancellation.**  That rearrangement leaves
:math:`\gamma - \kappa` to be formed by subtraction, and as :math:`\sigma \to 0`
those two agree to more and more digits.  At :math:`\sigma = 10^{-8}` the
subtraction has no significant digits left and the price comes back wrong in the
third decimal place -- measured at 5.5e-3 relative error against a fifty-digit
reference.  A vanishing vol-of-rate is not an exotic input: it is what a
deterministic-rate limit, a calibration starting point, and a finite-difference
sensitivity all walk through.

The fix is to never form the difference.  Since
:math:`\gamma^2 - \kappa^2 = 2\sigma^2`,

.. math::

    \delta := \gamma - \kappa = \frac{2\sigma^2}{\gamma + \kappa},

which is a *quotient of positive quantities* and avoids subtractive cancellation for small :math:`\sigma`.  With :math:`\delta` in hand the denominator becomes
:math:`(\gamma + \kappa) + \delta z`, and -- using
:math:`2\gamma = (\gamma + \kappa) + \delta` -- the affine base is

.. math::

    \frac{2\gamma}{(\gamma+\kappa) + \delta z} = \frac{1}{1 + x},
    \qquad x = -\frac{\delta (1 - z)}{2\gamma},

whose logarithm is :math:`-\log(1 + x)` with :math:`x \to 0` as
:math:`\sigma \to 0` -- exactly what :func:`math.log1p` exists for.  Finally
:math:`\frac{2\kappa\theta}{\sigma^2} \cdot \frac{\delta}{2} =
\frac{2\kappa\theta}{\gamma + \kappa}`, so the :math:`\sigma^2` in the exponent
cancels analytically instead of numerically.  What is left is
:func:`cir_affine_coefficients`.

Measured against ``mpmath`` at fifty digits, this form holds the relative error
in the *exponent* to under five units in the last place across the tested
parameter grid -- :math:`\sigma` from :math:`10^{-12}` to 5, maturities
to 500 years, :math:`\gamma\tau` past 3500.  The table is regenerated by
``scripts/generate_cir_reference_fixtures.py`` and pinned by
``tests/rates/test_reference_fixtures.py``.

There is **no** small-:math:`\sigma` threshold and no asymptotic branch.  The
only special case is :math:`\sigma` exactly zero, where the rate is
deterministic, :math:`2\kappa\theta/\sigma^2` is not a number, and the limit is
written out directly.

**Failure three: the complex logarithm.**  :func:`cir_integrated_rate_transform`
evaluates the same affine form at complex :math:`s`, and there the repair above
is silently undone by the backend.  NumPy, torch and JAX all compute a complex
``log1p`` as :math:`\log(1+z)` -- forming the sum first, which is exactly the
cancellation ``log1p`` exists to avoid.  Multiplied by the
:math:`2\kappa\theta/\sigma^2` standing in front of it, the lost digits are
amplified without bound as :math:`\sigma \to 0`: at :math:`\sigma = 10^{-6}` the
transform came back with a *relative error of 4e3*.  :func:`_log1p` restores it
with Kahan's decomposition and leaves the real path on the backend's own
``log1p``, bit for bit.

*The transform is the bond formula with an* :math:`s` *threaded through it,* and
that is what makes a transcription error hard to see: every wrong variant still
prices a bond, because at :math:`s = 1` the missing factor is one.  The detector is the small-:math:`\tau` expansion
:math:`\log A_s \approx -\kappa\theta s \tau^2 / 2`, whose two :math:`O(\tau)`
terms cancel only when the :math:`s` is present.  Unlike Heston's transform,
this one needs no branch bookkeeping at all, and that is a theorem rather than
an observation; :func:`cir_integrated_rate_coefficients` states it.

*This module is array-API native.*  It is written once against
:mod:`fast_vollib._array_api`, so the same code prices a bond from Python floats,
from a torch tensor that carries a gradient back to ``kappa``, and from a JAX
array under ``jit``.  It is the library's first analytic pricer with that
property; the Fourier pricers in :mod:`fast_vollib.pricing` are host-side
float64 by construction.

Parameterization is risk-neutral.  CIR's equation 23 carries a market price of
rate risk; ``kappa`` and ``theta`` here are the risk-neutral values with that
premium already absorbed, which is what a bond price needs and what a calibration
to bond data recovers.  Bakshi, Cao and Chen (1997) write the drift as
:math:`\theta_R - \kappa_R R`, so their parameters map on as
``kappa = kappa_R`` and ``theta = theta_R / kappa_R``.

The Feller ratio :math:`2\kappa\theta/\sigma^2` is reported by
:class:`~fast_vollib.rates.CIRDiscountCurve` and never enforced: calibrations
violate it routinely, the bond formula is well defined either way, and refusing
those parameters would make the library unable to represent the curves it exists
to fit.  CIR cannot produce a negative short rate; that is a property of the
model, stated rather than hidden.

References
----------
Cox, J. C., Ingersoll, J. E., Ross, S. A. (1985). A Theory of the Term Structure
of Interest Rates. *Econometrica* 53(2), 385-407, equation 23.

Bakshi, G., Cao, C., Chen, Z. (1997). Empirical Performance of Alternative
Option Pricing Models. *Journal of Finance* 52(5), 2003-2049.

Examples
--------
>>> from fast_vollib.rates import cir_discount_factor
>>> price = cir_discount_factor(
...     kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04, maturity=1.0
... )
>>> float(round(price, 12))
0.960840811993

A zero maturity is worth exactly one, and no branch is needed to make it so --
every term of the exponent vanishes on its own:

>>> float(cir_discount_factor(
...     kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04, maturity=0.0
... ))
1.0
"""

from __future__ import annotations

from typing import Any

import numpy as np

from .._array_api import concrete_float, get_namespace
from ._validate import ensure_scalar_parameter
from .errors import RateValidationError

__all__ = [
    "cir_affine_coefficients",
    "cir_discount_factor",
    "cir_instantaneous_forward_rate",
    "cir_integrated_rate_coefficients",
    "cir_integrated_rate_transform",
    "cir_zero_rate",
]


def _validated(kappa: Any, theta: Any, volatility: Any, maturity: Any) -> tuple[Any, Any, Any, Any]:
    """The four shared arguments, checked once, returned unchanged."""
    ensure_scalar_parameter(kappa, field="kappa", positive=True)
    ensure_scalar_parameter(theta, field="theta", non_negative=True)
    ensure_scalar_parameter(volatility, field="volatility", non_negative=True)
    ensure_scalar_parameter(maturity, field="maturity", non_negative=True)
    return kappa, theta, volatility, maturity


def _is_complex(value: Any) -> bool:
    """Whether ``value`` carries an imaginary part, in any backend."""
    dtype = getattr(value, "dtype", None)
    if dtype is not None:
        try:
            return bool(np.issubdtype(dtype, np.complexfloating))
        except TypeError:  # a torch dtype, which numpy cannot classify
            return "complex" in str(dtype)
    return isinstance(value, complex)


def _log1p(xp: Any, x: Any) -> Any:
    r"""``log(1 + x)``, accurate for small ``|x|`` -- including complex ``x``.

    **A backend's complex ``log1p`` is not a ``log1p``.**  NumPy's, torch's and
    JAX's all evaluate :math:`\log(1 + z)` by forming :math:`1 + z` and taking
    the complex logarithm, which is exactly the cancellation the real
    :func:`math.log1p` exists to avoid.  Measured against ``mpmath`` at fifty
    digits, ``numpy.log1p`` on a complex argument loses about one digit per
    decade of :math:`|z|`: 5.6e-11 relative at :math:`|z| \approx 10^{-6}` and
    6.3e-5 at :math:`10^{-12}`.

    That would silently undo this module's entire point.  The exponent carries
    :math:`2\kappa\theta/\sigma^2` in front of the logarithm, so a small
    vol-of-rate multiplies the error by a huge number: at
    :math:`\sigma = 10^{-6}` the integrated-rate transform at complex ``s``
    came back with a *relative error of 4e3* -- not a lost digit, a lost
    answer.

    The repair is Kahan's decomposition, which routes each part through an
    operation that is accurate on its own:

    .. math::

        \log(1 + z) = \tfrac{1}{2}\log\!\big(1 + (2x + x^2 + y^2)\big)
                      + i \arg(1 + z),

    with :math:`z = x + iy`.  The real part is a *real* ``log1p`` of a quantity
    that is formed without cancellation for small :math:`z`, and the imaginary
    part is an ``atan2``, which is accurate near the positive real axis by
    construction.  Measured the same way, this is exact to the last bit at
    every magnitude tried.

    The real branch is left as the backend's own ``log1p`` so that nothing
    about the array-API path -- values, dtypes, or gradients -- changes.
    """
    if not _is_complex(x):
        return xp.log1p(x)
    real = xp.real(x)
    imag = xp.imag(x)
    return 0.5 * xp.log1p(2.0 * real + (real * real + imag * imag)) + 1j * xp.angle(1.0 + x)


def _is_exactly_zero(value: Any) -> bool:
    """Whether ``value`` is concretely, exactly zero.

    A traced value returns ``False``: under a JAX transformation there is no
    number to compare, and taking the deterministic branch on a tracer would
    bake one model into a program written for the other. A caller who wants the
    deterministic limit under a trace states it by passing ``volatility=0.0`` as
    a Python float, which is concrete.
    """
    as_float = concrete_float(value)
    return as_float is not None and as_float == 0.0


def cir_affine_coefficients(
    *, kappa: Any, theta: Any, volatility: Any, maturity: Any
) -> tuple[Any, Any]:
    r"""``(log_A, B)`` for ``P(0, maturity) = exp(log_A - B * initial_rate)``.

    The logarithm of :math:`A` rather than :math:`A` itself, because
    :math:`A` underflows to zero long before the exponent stops being a
    perfectly ordinary number -- a 200-year bond at a vol-of-rate of 2 has
    :math:`\log A \approx -800`.

    Parameters
    ----------
    kappa : float or scalar array
        Mean-reversion speed, strictly positive.
    theta : float or scalar array
        Long-run short rate, non-negative.
    volatility : float or scalar array
        Vol-of-rate :math:`\sigma`, non-negative. Zero takes the exact
        deterministic branch.
    maturity : float or scalar array
        Year fraction, non-negative.

    Returns
    -------
    tuple
        ``(log_A, B)``, in the namespace, dtype, and device of the inputs.

    Notes
    -----
    Independent of ``initial_rate`` by construction: that is what "affine in the
    state" means, and it is why one pair of coefficients prices a whole curve.

    Examples
    --------
    >>> from fast_vollib.rates import cir_affine_coefficients
    >>> log_a, b = cir_affine_coefficients(
    ...     kappa=0.3, theta=0.04, volatility=0.1, maturity=1.0
    ... )
    >>> float(round(b, 10))
    0.8627011879
    """
    kappa, theta, volatility, maturity = _validated(kappa, theta, volatility, maturity)
    xp = get_namespace(kappa, theta, volatility, maturity)

    if _is_exactly_zero(volatility):
        # P = exp(-theta*tau - (r0 - theta)(1 - e^{-kappa tau})/kappa), i.e.
        # log_A = -theta*tau + theta*B and B = (1 - e^{-kappa tau})/kappa.
        b = (1.0 - xp.exp(-kappa * maturity)) / kappa
        return -theta * maturity + theta * b, b

    gamma = xp.sqrt(kappa * kappa + 2.0 * volatility * volatility)
    # gamma - kappa, formed as a quotient so it never loses a digit. See the
    # module docstring: the subtraction is the whole problem.
    delta = 2.0 * volatility * volatility / (gamma + kappa)
    z = xp.exp(-gamma * maturity)
    denominator = (gamma + kappa) + delta * z
    b = 2.0 * (1.0 - z) / denominator
    # denominator / (2 * gamma) == 1 + x exactly, because 2*gamma == (gamma+kappa) + delta.
    x = -delta * (1.0 - z) / (2.0 * gamma)
    log_a = -2.0 * kappa * theta * maturity / (gamma + kappa) - (
        2.0 * kappa * theta / (volatility * volatility)
    ) * xp.log1p(x)
    return log_a, b


def cir_discount_factor(
    *, kappa: Any, theta: Any, volatility: Any, initial_rate: Any, maturity: Any
) -> Any:
    r"""``P(0, maturity)``, the zero-coupon bond price under CIR.

    Parameters
    ----------
    kappa, theta, volatility : float or scalar array
        See :func:`cir_affine_coefficients`.
    initial_rate : float or scalar array
        The short rate now, :math:`r_0`, non-negative.
    maturity : float or scalar array
        Year fraction, non-negative. Zero returns exactly ``1.0``.

    Returns
    -------
    The discount factor, in the caller's namespace, dtype, and device.

    Notes
    -----
    ``maturity == 0`` needs no special case: at :math:`\tau = 0` we have
    :math:`z = 1`, so :math:`B = 0`, :math:`x = 0`, ``log1p(0) == 0``, and the
    whole exponent is exactly zero. A branch would only add a place for the two
    paths to disagree.

    Examples
    --------
    >>> from fast_vollib.rates import cir_discount_factor
    >>> float(round(cir_discount_factor(
    ...     kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04, maturity=10.0
    ... ), 12))
    0.677896707097
    """
    ensure_scalar_parameter(initial_rate, field="initial_rate", non_negative=True)
    kappa, theta, volatility, maturity = _validated(kappa, theta, volatility, maturity)
    xp = get_namespace(kappa, theta, volatility, initial_rate, maturity)
    log_a, b = cir_affine_coefficients(
        kappa=kappa, theta=theta, volatility=volatility, maturity=maturity
    )
    return xp.exp(log_a - b * initial_rate)


def cir_zero_rate(
    *, kappa: Any, theta: Any, volatility: Any, initial_rate: Any, maturity: Any
) -> Any:
    r"""The continuously compounded zero rate ``-log P(0, tau) / tau``.

    At ``maturity == 0`` the quotient is :math:`0/0`; the limit is the short
    rate itself, which is returned. That value is the *definition* of the short
    rate, not an approximation to it.

    Examples
    --------
    >>> from fast_vollib.rates import cir_zero_rate
    >>> cir_zero_rate(
    ...     kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04, maturity=0.0
    ... )
    0.04
    """
    ensure_scalar_parameter(initial_rate, field="initial_rate", non_negative=True)
    kappa, theta, volatility, maturity = _validated(kappa, theta, volatility, maturity)
    if _is_exactly_zero(maturity):
        return initial_rate
    log_a, b = cir_affine_coefficients(
        kappa=kappa, theta=theta, volatility=volatility, maturity=maturity
    )
    return (b * initial_rate - log_a) / maturity


def cir_instantaneous_forward_rate(
    *, kappa: Any, theta: Any, volatility: Any, initial_rate: Any, maturity: Any
) -> Any:
    r"""``f(0, tau) = -d log P(0, tau) / d tau``, evaluated analytically.

    Differentiating the closed form directly would reintroduce the cancellation
    the module exists to avoid.  Instead the derivative is read off the Riccati
    system the affine coefficients solve,

    .. math::

        \frac{dB}{d\tau} = 1 - \kappa B - \tfrac{1}{2}\sigma^2 B^2,
        \qquad
        \frac{d \log A}{d\tau} = -\kappa\theta B,

    so that

    .. math::

        f(0, \tau) = \kappa\theta B(\tau)
                     + r_0\left(1 - \kappa B(\tau) - \tfrac{1}{2}\sigma^2 B(\tau)^2\right),

    which needs only :math:`B`, and :math:`B` is already exact.  At
    :math:`\tau = 0` this gives :math:`B = 0` and therefore
    :math:`f(0, 0) = r_0`, as it must.

    Examples
    --------
    >>> from fast_vollib.rates import cir_instantaneous_forward_rate
    >>> float(cir_instantaneous_forward_rate(
    ...     kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04, maturity=0.0
    ... ))
    0.04
    """
    ensure_scalar_parameter(initial_rate, field="initial_rate", non_negative=True)
    kappa, theta, volatility, maturity = _validated(kappa, theta, volatility, maturity)
    _log_a, b = cir_affine_coefficients(
        kappa=kappa, theta=theta, volatility=volatility, maturity=maturity
    )
    return kappa * theta * b + initial_rate * (
        1.0 - kappa * b - 0.5 * volatility * volatility * b * b
    )


def _reject_singular_transform(s: Any, kappa: Any, volatility: Any) -> None:
    """Restrict evaluation to the principal-square-root representation's domain.

    A non-positive real discriminant needs a separate limiting or trigonometric
    representation. This API does not implement it. This restriction is NOT
    the finite-horizon moment-explosion boundary: some excluded expectations
    are finite, depending on maturity. Concrete values are checked eagerly;
    traced callers remain responsible for the documented domain.
    """
    try:
        argument = np.asarray(kappa) ** 2 + 2.0 * np.asarray(volatility) ** 2 * np.asarray(s)
    except Exception:  # pragma: no cover - a traced or unreadable input
        return
    if argument.dtype == object or not np.issubdtype(argument.dtype, np.number):
        return
    on_the_cut = (np.imag(argument) == 0.0) & (np.real(argument) <= 0.0)
    if bool(np.any(on_the_cut)):
        raise RateValidationError(
            "cir_integrated_rate_transform needs kappa**2 + 2*volatility**2*s off the "
            "non-positive real axis. This is a representation-domain restriction, "
            "not a claim that the finite-horizon expectation is infinite."
        )


def cir_integrated_rate_coefficients(
    s: Any, *, kappa: Any, theta: Any, volatility: Any, maturity: Any
) -> tuple[Any, Any]:
    r"""``(log_A_s, B_s)`` for ``Psi(s) = exp(log_A_s - B_s * initial_rate)``.

    The affine coefficients of the *integrated-rate* transform

    .. math::

        \Psi(s) = E\!\left[
            \exp\!\left(-s \int_0^\tau r_u\,du\right) \,\middle|\, r_0
        \right],

    for complex :math:`s`.  At :math:`s = 1` this is the zero-coupon bond and
    the coefficients are :func:`cir_affine_coefficients`'; the general case is
    what a stochastic-rate transform method needs, because the discounting and
    the payoff are functions of the same path and the two cannot be separated.

    Parameters
    ----------
    s : complex, float, or array
        The transform argument.  Arrays are evaluated elementwise, which is how
        a quadrature over :math:`u` with :math:`s = 1 - iu` is taken in one
        call.
    kappa, theta, volatility, maturity : float or scalar array
        As in :func:`cir_affine_coefficients`.

    Returns
    -------
    tuple
        ``(log_A_s, B_s)``, broadcast to the shape of ``s``.

    Raises
    ------
    RateValidationError
        If ``s`` is real and at or below ``-kappa**2 / (2 * volatility**2)``,
        outside this representation's domain. Also a :class:`ValueError`.

    Notes
    -----
    **The** :math:`s` **in the first term is not optional.**  Writing
    :math:`\delta_s = 2\sigma^2 s/(\gamma_s + \kappa)` gives

    .. math::

        -\frac{2\kappa\theta}{\sigma^2}\cdot\frac{\delta_s \tau}{2}
            = -\frac{2\kappa\theta\, s\, \tau}{\gamma_s + \kappa},

    which is the form evaluated here: it cancels :math:`\sigma^2` analytically
    and carries the :math:`s` explicitly.  Dropping that :math:`s` -- the
    transcription that turns this back into the bond formula -- leaves
    a result that is still correct at :math:`s = 1` and wrong everywhere else.
    The small-:math:`\tau` expansion is the cheap detector, because the two
    :math:`O(\tau)` terms cancel only with the :math:`s` present:

    .. math:: \log A_s = -\tfrac{1}{2}\kappa\theta\, s\, \tau^2 + O(\tau^3).

    **No branch tracking is needed, and that is a theorem rather than an
    observation.**  Since :math:`\gamma_s^2 - \kappa^2 = 2\sigma^2 s`, the
    quantity :math:`\delta_s` is exactly :math:`\gamma_s - \kappa`, so

    .. math::

        1 + x_s = \frac{(\gamma_s + \kappa) + (\gamma_s - \kappa) z_s}{2\gamma_s},
        \qquad z_s = e^{-\gamma_s \tau},\ |z_s| \le 1 .

    The principal square root puts :math:`\mathrm{Re}\,\gamma_s > 0`, and
    :math:`|\gamma_s + \kappa|^2 - |\gamma_s - \kappa|^2 = 4\kappa\,
    \mathrm{Re}\,\gamma_s > 0`, so as :math:`\tau` runs from :math:`0` to
    :math:`\infty` the point :math:`1 + x_s` stays inside the open disk of
    radius :math:`|\gamma_s - \kappa| / |2\gamma_s|` about
    :math:`(\gamma_s + \kappa) / (2\gamma_s)`.  That disk excludes the origin,
    so it lies in an open half-plane through the origin; its argument therefore
    spans an interval of width less than :math:`\pi` containing
    :math:`\arg 1 = 0`, and the principal :math:`\log(1+x)` never reaches
    :math:`\pm\pi`.  Heston's transform has no such bound -- its
    :math:`(a-d)/(a+d)` can and does wind -- which is why that one needs the
    branch bookkeeping and this one does not.

    Examples
    --------
    >>> from fast_vollib.rates import cir_integrated_rate_coefficients
    >>> log_a, b = cir_integrated_rate_coefficients(
    ...     1.0, kappa=0.3, theta=0.04, volatility=0.1, maturity=1.0
    ... )
    >>> float(round(b, 10))
    0.8627011879

    A complex argument is ordinary here:

    >>> log_a, b = cir_integrated_rate_coefficients(
    ...     1.0 - 0.5j, kappa=0.3, theta=0.04, volatility=0.1, maturity=1.0
    ... )
    >>> complex(round(b.real, 10), round(b.imag, 10))
    (0.8630096154-0.4307323759j)
    """
    kappa, theta, volatility, maturity = _validated(kappa, theta, volatility, maturity)
    _reject_singular_transform(s, kappa, volatility)
    xp = get_namespace(s, kappa, theta, volatility, maturity)

    if _is_exactly_zero(volatility):
        # The rate is deterministic, so the integral is too and the transform is
        # the bond exponent times s exactly:
        #   Psi(s) = exp(-s * (theta*tau + (r0 - theta)*(1 - e^{-kappa tau})/kappa)).
        b = (1.0 - xp.exp(-kappa * maturity)) / kappa
        return s * (-theta * maturity + theta * b), s * b

    gamma = xp.sqrt(kappa * kappa + 2.0 * volatility * volatility * s)
    # delta == gamma - kappa, formed as a quotient rather than a difference for
    # the reason the module docstring gives: at small volatility the two agree
    # to every digit float64 has.
    delta = 2.0 * volatility * volatility * s / (gamma + kappa)
    z = xp.exp(-gamma * maturity)
    denominator = (gamma + kappa) + delta * z
    b = 2.0 * s * (1.0 - z) / denominator
    x = -delta * (1.0 - z) / (2.0 * gamma)
    log_a = -2.0 * kappa * theta * s * maturity / (gamma + kappa) - (
        2.0 * kappa * theta / (volatility * volatility)
    ) * _log1p(xp, x)
    return log_a, b


def cir_integrated_rate_transform(
    s: Any, *, kappa: Any, theta: Any, volatility: Any, initial_rate: Any, maturity: Any
) -> Any:
    r"""``E[exp(-s * int_0^tau r_u du) | r_0]`` under CIR, for complex ``s``.

    Parameters
    ----------
    s : complex, float, or array
        See :func:`cir_integrated_rate_coefficients`.
    kappa, theta, volatility, maturity : float or scalar array
    initial_rate : float or scalar array
        The short rate now, non-negative.

    Returns
    -------
    The transform, broadcast to the shape of ``s``.

    Notes
    -----
    ``Psi(1)`` is the zero-coupon bond price and is computed by an arithmetic
    path that reduces, term for term, to :func:`cir_discount_factor`'s -- the
    two agree to the bit, which is asserted by test rather than assumed.
    ``Psi(0)`` is exactly ``1`` with no special case: at :math:`s = 0` we have
    :math:`\gamma_0 = \kappa`, :math:`\delta_0 = 0`, hence :math:`B_0 = 0`,
    :math:`x_0 = 0`, and the whole exponent vanishes.

    Examples
    --------
    >>> from fast_vollib.rates import cir_discount_factor, cir_integrated_rate_transform
    >>> curve = dict(kappa=0.3, theta=0.04, volatility=0.1, initial_rate=0.04)
    >>> psi = cir_integrated_rate_transform(1.0, maturity=2.0, **curve)
    >>> bool(psi == cir_discount_factor(maturity=2.0, **curve))
    True
    >>> float(cir_integrated_rate_transform(0.0, maturity=2.0, **curve))
    1.0
    """
    ensure_scalar_parameter(initial_rate, field="initial_rate", non_negative=True)
    log_a, b = cir_integrated_rate_coefficients(
        s, kappa=kappa, theta=theta, volatility=volatility, maturity=maturity
    )
    xp = get_namespace(log_a, b, initial_rate)
    return xp.exp(log_a - b * initial_rate)
