"""The Heston surface: no market needed, wings declined honestly, parameters recovered."""

from __future__ import annotations

import json

import numpy as np
import pytest

from fast_vollib.surface import (
    SurfaceGridSpec,
    SurfaceMarket,
    SurfaceObservations,
    SurfacePoints,
    materialize_surface,
)
from fast_vollib.surface.errors import SurfaceCalibrationError, SurfaceValidationError
from fast_vollib.surface.fitting.heston import (
    DEFAULT_IV_UNCERTAINTY_TOLERANCE,
    PRICE_NOISE_PER_UNIT_FORWARD,
    HestonCalibrator,
    HestonIVSurface,
    HestonParameters,
)
from fast_vollib.surface.protocols import DefiniteIVSurface, SurfaceCalibrator

TRUTH = HestonParameters(v0=0.045, kappa=1.8, theta=0.055, vol_of_vol=0.55, rho=-0.65)
MATURITIES = (0.08, 0.17, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0)

#: Parameter recovery from noiseless data generated by the same code path.  The
#: binding constraint is the solver's own convergence criterion together with the
#: finite-difference step; measured worst case over the five parameters is 8e-7.
RECOVERY_TOL = 5e-6

#: How closely the fitted surface must reproduce the implied volatilities it was
#: fitted to.  Measured at 1e-8 -- eight decimal places of a volatility.
FIT_TOL = 1e-6


def _observations(parameters: HestonParameters = TRUTH, n_k: int = 21, span: float = 0.45):
    surface = HestonIVSurface(parameters=parameters)
    k = np.tile(np.linspace(-span, span, n_k), len(MATURITIES))
    T = np.repeat(MATURITIES, n_k)
    iv = surface.implied_volatility(k, T)
    resolved = np.isfinite(iv)
    return SurfaceObservations(k=k[resolved], T=T[resolved], iv=iv[resolved])


# --- the parameters ------------------------------------------------------------


@pytest.mark.parametrize(
    "kwargs, message",
    [
        ({"v0": 0.0}, "v0 must be strictly positive"),
        ({"kappa": -1.0}, "kappa must be strictly positive"),
        ({"theta": 0.0}, "theta must be strictly positive"),
        ({"vol_of_vol": 0.0}, "vol_of_vol must be strictly positive"),
        ({"rho": 1.0}, "rho must lie strictly inside"),
        ({"v0": np.inf}, "v0 must be finite"),
    ],
)
def test_invalid_parameters_are_refused(kwargs, message) -> None:
    base = {"v0": 0.04, "kappa": 2.0, "theta": 0.04, "vol_of_vol": 0.3, "rho": -0.7}
    with pytest.raises(SurfaceValidationError, match=message):
        HestonParameters(**{**base, **kwargs})


def test_the_feller_ratio_is_reported_not_enforced() -> None:
    violating = HestonParameters(v0=0.04, kappa=0.5, theta=0.06, vol_of_vol=0.9, rho=-0.9)
    assert violating.satisfies_feller is False
    assert violating.feller_ratio == pytest.approx(2 * 0.5 * 0.06 / 0.81, rel=1e-12)


def test_the_parameters_carry_across_to_the_process_unchanged() -> None:
    process = TRUTH.to_process(drift=0.03)
    assert dict(process.params()) == {
        "kappa": TRUTH.kappa,
        "theta": TRUTH.theta,
        "vol_of_vol": TRUTH.vol_of_vol,
        "rho": TRUTH.rho,
        "drift": 0.03,
    }


def test_the_parameter_mapping_is_json_safe_plain_data() -> None:
    payload = TRUTH.parameters()
    assert json.loads(json.dumps(payload, allow_nan=False)) == payload


# --- the surface ---------------------------------------------------------------


def test_the_surface_needs_no_market_state() -> None:
    """In forward log-moneyness the forward divides out of price and strike.

    Passing a market must therefore change nothing, and *not* passing one must
    not raise -- unlike a computation that genuinely needs one, which raises
    rather than assuming a unit forward.
    """
    surface = HestonIVSurface(parameters=TRUTH)
    points = SurfacePoints(k=[-0.2, 0.0, 0.2], T=[1.0, 1.0, 1.0])
    without = surface.evaluate(points)
    with_market = surface.evaluate(
        points, market=SurfaceMarket.from_spot(spot=4321.0, T=[1.0], rate=0.05, carry=0.02)
    )
    np.testing.assert_array_equal(without.iv, with_market.iv)


def test_a_negative_correlation_skews_the_smile_downward_in_strike() -> None:
    surface = HestonIVSurface(parameters=TRUTH)
    k = np.linspace(-0.3, 0.3, 13)
    iv = surface.implied_volatility(k, np.full(k.size, 1.0))
    assert iv[0] > iv[-1]


def test_a_zero_correlation_smile_is_symmetric_about_the_money() -> None:
    # Not exactly symmetric -- the log-normal drift breaks it -- but the two
    # wings must be far closer to each other than under a -0.65 correlation.
    symmetric = HestonParameters(v0=0.045, kappa=1.8, theta=0.055, vol_of_vol=0.55, rho=0.0)
    k = np.array([-0.3, 0.3])
    flat = HestonIVSurface(parameters=symmetric).implied_volatility(k, np.full(2, 1.0))
    skewed = HestonIVSurface(parameters=TRUTH).implied_volatility(k, np.full(2, 1.0))
    assert abs(flat[0] - flat[1]) < 0.1 * abs(skewed[0] - skewed[1])


def test_the_surface_declines_wings_it_cannot_resolve() -> None:
    """The Fourier price has absolute accuracy, so a low-vega point is declined.

    This is the contract a definite surface owes: it either answers or says it
    will not, and never returns a plausible number it does not stand behind.
    """
    surface = HestonIVSurface(parameters=TRUTH)
    k = np.linspace(-1.5, 1.5, 31)
    T = np.full(k.size, 0.05)
    iv = surface.implied_volatility(k, T)
    uncertainty = surface.inversion_uncertainty(k, T)
    resolved = np.isfinite(iv)
    assert bool(np.any(resolved)) and bool(np.any(~resolved))
    assert bool(np.all(uncertainty[resolved] <= DEFAULT_IV_UNCERTAINTY_TOLERANCE))


def test_every_answered_point_is_accurate_to_the_declared_tolerance() -> None:
    """The declared tolerance is a measured guarantee, not a hope.

    Doubling the quadrature nodes twice over is an independent evaluation; a
    point the surface answered must agree between the two by less than the
    uncertainty it declared, or the guard is not doing its job.
    """
    coarse = HestonIVSurface(parameters=TRUTH, n_nodes=768)
    fine = HestonIVSurface(parameters=TRUTH, n_nodes=4096)
    k = np.linspace(-1.2, 1.2, 25)
    for maturity in (0.05, 0.25, 1.0, 3.0):
        T = np.full(k.size, maturity)
        left = coarse.implied_volatility(k, T)
        right = fine.implied_volatility(k, T)
        both = np.isfinite(left) & np.isfinite(right)
        if not bool(np.any(both)):
            continue
        assert float(np.max(np.abs(left - right)[both])) < DEFAULT_IV_UNCERTAINTY_TOLERANCE


def test_the_declared_price_noise_is_the_one_the_guard_uses() -> None:
    # The guard is uncertainty = noise / vega; at a point whose uncertainty is
    # exactly the tolerance, the vega is the ratio of the two constants.
    assert PRICE_NOISE_PER_UNIT_FORWARD > 0.0
    surface = HestonIVSurface(parameters=TRUTH)
    k = np.array([0.0])
    T = np.array([1.0])
    uncertainty = surface.inversion_uncertainty(k, T)
    assert 0.0 < float(uncertainty[0]) < DEFAULT_IV_UNCERTAINTY_TOLERANCE


def test_the_materialized_surface_passes_the_mesh_arbitrage_harness() -> None:
    """A model price comes from a martingale measure, so the mesh should be clean.

    The claim asserted is about the *mesh*, which is what was measured; the
    module docstring is explicit that the model's own arbitrage freedom is a
    different statement and that a finite grid can trip on wing noise.
    """
    grid = SurfaceGridSpec(k=np.linspace(-0.35, 0.35, 21), T=list(MATURITIES))
    report = materialize_surface(HestonIVSurface(parameters=TRUTH), grid).validate()
    assert report.passed is True, report.metrics


def test_total_variance_and_implied_volatility_agree() -> None:
    surface = HestonIVSurface(parameters=TRUTH)
    k = np.linspace(-0.3, 0.3, 9)
    T = np.full(k.size, 0.75)
    np.testing.assert_allclose(
        surface.total_variance(k, T),
        surface.implied_volatility(k, T) ** 2 * T,
        rtol=1e-14,
        atol=0.0,
    )


def test_evaluation_returns_rows_in_query_order() -> None:
    surface = HestonIVSurface(parameters=TRUTH)
    points = SurfacePoints(k=[0.2, -0.2, 0.0], T=[1.0, 1.0, 1.0])
    prediction = surface.evaluate(points)
    assert prediction.points.equals(points)
    np.testing.assert_array_equal(prediction.iv, surface.implied_volatility(points.k, points.T))


@pytest.mark.parametrize(
    "kwargs, message",
    [
        ({"parameters": "not-parameters"}, "parameters must be HestonParameters"),
        ({"iv_uncertainty_tolerance": 0.0}, "iv_uncertainty_tolerance must be finite"),
    ],
)
def test_invalid_surface_configuration_is_refused(kwargs, message) -> None:
    with pytest.raises(SurfaceValidationError, match=message):
        HestonIVSurface(**{"parameters": TRUTH, **kwargs})


# --- calibration ---------------------------------------------------------------


def test_calibration_recovers_the_parameters_it_was_generated_from() -> None:
    fitted = HestonCalibrator().fit(_observations())
    for name, value in TRUTH.as_mapping().items():
        assert abs(getattr(fitted.parameters, name) - value) < RECOVERY_TOL, name


def test_the_fitted_surface_reproduces_the_quotes_it_was_fitted_to() -> None:
    observations = _observations()
    fitted = HestonCalibrator().fit(observations)
    predicted = fitted.implied_volatility(observations.k, observations.T)
    resolved = np.isfinite(predicted)
    rmse = float(np.sqrt(np.mean((predicted[resolved] - observations.iv[resolved]) ** 2)))
    assert rmse < FIT_TOL, rmse


def test_calibration_is_deterministic() -> None:
    observations = _observations()
    first = HestonCalibrator().fit(observations)
    second = HestonCalibrator().fit(observations)
    assert first.parameters.as_mapping() == second.parameters.as_mapping()


def test_the_calibrator_holds_no_state_between_fits() -> None:
    calibrator = HestonCalibrator(n_starts=1)
    other = HestonParameters(v0=0.02, kappa=3.0, theta=0.03, vol_of_vol=0.4, rho=-0.4)
    first = calibrator.fit(_observations())
    calibrator.fit(_observations(other))
    third = calibrator.fit(_observations())
    assert first.parameters.as_mapping() == third.parameters.as_mapping()


def test_calibration_survives_noisy_quotes() -> None:
    generator = np.random.default_rng(20260831)
    clean = _observations()
    noise = 0.002
    noisy = SurfaceObservations(
        k=clean.k, T=clean.T, iv=clean.iv + noise * generator.standard_normal(clean.n)
    )
    fitted = HestonCalibrator().fit(noisy)
    predicted = fitted.implied_volatility(noisy.k, noisy.T)
    resolved = np.isfinite(predicted)
    rmse = float(np.sqrt(np.mean((predicted[resolved] - noisy.iv[resolved]) ** 2)))
    # The fit should land near the injected noise level: far below means it is
    # interpolating the noise, far above means it has not converged.
    assert 0.2 * noise < rmse < 5.0 * noise


@pytest.mark.parametrize(
    "observations, message",
    [
        (
            SurfaceObservations(
                k=np.linspace(-0.2, 0.2, 6), T=np.full(6, 1.0), iv=np.full(6, np.nan)
            ),
            "no surface to fit",
        ),
        (
            SurfaceObservations(k=[-0.1, 0.0, 0.1], T=[1.0] * 3, iv=[0.22, 0.20, 0.21]),
            "not identified",
        ),
    ],
    ids=["all-missing", "too-few"],
)
def test_an_unfittable_observation_set_is_refused(observations, message) -> None:
    with pytest.raises(SurfaceCalibrationError, match=message):
        HestonCalibrator().fit(observations)


@pytest.mark.parametrize(
    "kwargs, message",
    [
        ({"objective": "vega"}, "objective must be one of"),
        ({"n_starts": 0}, "n_starts must be at least 1"),
        ({"max_iterations": 0}, "max_iterations must be at least 1"),
        ({"diff_step": 0.0}, "diff_step must lie strictly inside"),
    ],
)
def test_invalid_calibrator_configuration_is_refused(kwargs, message) -> None:
    with pytest.raises(SurfaceValidationError, match=message):
        HestonCalibrator(**kwargs)


def test_the_price_objective_also_fits_the_surface() -> None:
    fitted = HestonCalibrator(objective="price", n_starts=2).fit(_observations())
    predicted = fitted.implied_volatility(_observations().k, _observations().T)
    resolved = np.isfinite(predicted)
    rmse = float(np.sqrt(np.mean((predicted[resolved] - _observations().iv[resolved]) ** 2)))
    # A price residual is dominated by at-the-money vega, so the implied-vol fit
    # it produces is looser than the implied-vol objective's -- which is exactly
    # why the latter is the default.
    assert rmse < 1e-2


# --- the protocols -------------------------------------------------------------


def test_the_heston_types_satisfy_the_protocols_they_claim() -> None:
    assert isinstance(HestonIVSurface(parameters=TRUTH), DefiniteIVSurface)
    assert isinstance(HestonCalibrator(), SurfaceCalibrator)
